version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
    - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: install-dependencies
        command: npm install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run:
        name: linter
        command: npm run lint
    - run:
        name: test
        command: npm test
    - run:
        name: code-coverage
        command: npm run coverage
        when: always
    - run:
        name: Compress Coverage Reports
        command: tar -cvf coverage.tar ~/repo/coverage/lcov-report
    - store_artifacts:
        path: coverage.tar
        destination: coverage_report
    - run:
        name: Add Dokku to known_hosts
        command: |
        # ssh-keygen -R ec2-13-232-92-91.ap-south-1.compute.amazonaws.com
        # ssh-keygen -R 13.232.92.91
        # ssh-keygen -R ec2-13-232-92-91.ap-south-1.compute.amazonaws.com,13.232.92.91
        # ssh-keyscan -H ec2-13-232-92-91.ap-south-1.compute.amazonaws.com,13.232.92.91 >> ~/.ssh/known_hosts
        ssh-keyscan -H 52.90.114.53 >> ~/.ssh/known_hosts
        ssh-keyscan -H ec2-52-90-114-53.compute-1.amazonaws.com:sifi-frontend >> ~/.ssh/known_hosts
    - run:
        name: Deploy to Dokku
        command: git push -f dokku@ec2-52-90-114-53.compute-1.amazonaws.com:sifi-backend master

        